### ISSUE TITLE
Pinout2 -> Pinout.xyz

### ISSUE THREAD

**Issue by lurch** [Gadgetoid/Pinout.xyz#148]
Now that @Gadgetoid has renamed the repo, I guess all these references https://github.com/Gadgetoid/Pinout.xyz/search?p=1&q=pinout2&utf8=%E2%9C%93 ought to be updated to say `Pinout.xyx` instead?

**Comment by RogueM** [comment]
I guess so... They are hidden references that will be redirected correctly, but it wouldn't hurt to correct. Will get right on it!

**Comment by RogueM** [comment]
fixed!

**Comment by lurch** [comment]
You missed some?
https://github.com/Gadgetoid/Pinout.xyz/search?p=1&q=pinout2&utf8=%E2%9C%93

**Comment by RogueM** [comment]
cheers!

**Comment by lurch** [comment]
Great :-D
